###
GET http://localhost:3000/activities

###
GET http://localhost:3000/activities/activity/27

###
POST http://localhost:3000/activities/activity
Content-Type: application/json

{
    "title": "test activity",
    "description": "test description",
    "category_id": 1
}

### Test récupération des multimédias associés à une activité
GET http://localhost:3000/activities/24/multimedia
Content-Type: application/json

###

### Test ajout de multimédia à une activité
PUT http://localhost:3000/activities/25/multimedia
Content-Type: application/json

{
    "multimediaId": 2
}

###

### Test suppression d'un multimédia d'une activité
DELETE http://localhost:3000/activities/25/multimedia/2
Content-Type: application/json
