### Récupération de toutes les activités
GET http://localhost:3000/activities

### Récupération d'une activité spécifique par son id
GET http://localhost:3000/activities/27

### Création d'une nouvelle activité
POST http://localhost:3000/activities
Content-Type: application/json

{
    "title": "test activity",
    "description": "test description",
    "category_id": 7
}

