### Récupération de tous les utilisateurs
GET http://localhost:3000/users
Content-Type: application/json

###

### Récupération d'un utilisateur spécifique par ID
GET http://localhost:3000/users/3
Content-Type: application/json

###

### Création/Inscription d'un nouvel utilisateur
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "donald.trump@example.com",
  "password": "password123",
  "firstname": "Donald",
  "lastname": "Trump",
  "birthday": "1990-01-15",
  "phone_number": "1234567890"
}

###

### Mise à jour d'un profil utilisateur
PATCH http://localhost:3000/users/6
Content-Type: application/json

{
  "firstname": "Edouard",
  "lastname": "paul",
  "birthday": "1989-06-18",
  "phone_number": 847384958,
  "email": "edouard.paul@gmail.com",
  "password": "password343421",
  "image": "http://letrousansfin.jpg",
}

###

### Mise à jour du mot de passe de l'utilisateur
PATCH http://localhost:3000/users/19
Content-Type: application/json
Authorization: Bearer votre_jeton_jwt_valide

{
  "password": "newSecurePassword123"
}

###

### Connexion via email
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "donald.trump@example.com",
  "password": "password123"
}

###

### Suppression d'un utilisateur
DELETE http://localhost:3000/users/7
Content-Type: application/json
