###
GET http://localhost:3000/payments

###
GET http://localhost:3000/payments/payment/3

###
POST http://localhost:3000/payments/payment
Content-Type: application/json

{
    "amount": "100.00",
    "status": "pending",
    "date_amount": "2024-11-02",
    "reservation_id": 9,
    "stripe_payment_id": "sp_ghi787"


}

###
PATCH http://localhost:3000/payments/6/modify
Content-Type: application/json

{
    "amount": "150.00",
    "status": "pending",
    "date_amount": "2024-11-02",
    "reservation_id": 9,
    "stripe_payment_id": "sp_ghi787"
}

###
DELETE http://localhost:3000/payments/6/delete
