### Récupération de tous les utilisateurs
GET http://localhost:3000/users
Content-Type: application/json

###

### Récupération d'un utilisateur spécifique par ID
GET http://localhost:3000/users/3
Content-Type: application/json

###

### Création/Inscription d'un nouvel utilisateur (incluant le mot de passe)
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test.test@example.com",
  "password": "password123",
  "firstname": "MrTest",
  "lastname": "Testament",
  "birthday": "1990-01-15",
  "phone_number": "1234567890",
  "role_id": 1
}


### Mise à jour d'un profil utilisateur (sans changer le mot de passe)
PATCH http://localhost:3000/users/32
Content-Type: application/json

{
  "firstname": "TestModifié",
  "lastname": "TestMomifié",
  "birthday": "1989-06-18",
  "phone_number": "123456789",
  "email": "retest.retétést@gmail.com"
}

###

### Suppression d'un utilisateur
DELETE http://localhost:3000/users/28
Content-Type: application/json
