### Obtenir tous les multimédias des activités
GET http://localhost:3000/activities/multimedia

### Ajouter un multimédia à une activité
PUT http://localhost:3000/activities/27/multimedia/1


### Supprimer un multimédia d'une activité
DELETE http://localhost:3000/activities/5/multimedia/10